### ISSUE TITLE
Error: cannot find icon '...'

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3024]
```console
$ "Xpra-Python3-x86_64_4.1-r28395\xpra_cmd" attach ssh://user@ip/3 --ssh="plink -ssh -agent" --modal-windows=no --title="@title@ on @@/@server-display@" --headerbar=off --opengl=no --bandwidth-limit=6Mbps

XPRA_CUSTOM_TITLE_BAR=0
XPRA_EXECUTABLE=Xpra-Python3-x86_64_4.1-r28395
XPRA_REPAINT_ALL=1
XPRA_SCROLL_ENCODING=0

2021-02-08 10:34:48,240 Xpra GTK3 client version v4.0.6-94-g409d585fe 64-bit
2021-02-08 10:34:48,243  running on Microsoft Windows 10
2021-02-08 10:34:56,587 GStreamer version 1.18.2 for Python 3.8.7 64-bit
2021-02-08 10:34:56,911 created named pipe 'Xpra\11884'
2021-02-08 10:34:57,224 keyboard layout code 0x409
2021-02-08 10:34:57,225 identified as 'United States - English' : us
2021-02-08 10:34:57,584  keyboard settings: layout=us
2021-02-08 10:34:57,602  desktop size is 4160x1440 with 1 screen:
2021-02-08 10:34:57,632   Default (1100x381 mm - DPI: 96x96) workarea: 4160x1400
2021-02-08 10:34:57,632     Generic PnP Monitor 1600x900 at 0x534 (309x174 mm - DPI: 132x131) workarea: 1600x860 at 0x534
2021-02-08 10:34:57,633     C32JG5x 2560x1440 at 1600x0 (697x392 mm - DPI: 93x93) workarea: 2560x1400 at 1600x0
2021-02-08 10:34:58,534 Error: cannot find icon 'xpra'
2021-02-08 10:35:02,750 enabled remote logging
2021-02-08 10:35:02,754 Xpra GTK3 X11 server version 3.0.13-r28292 64-bit
2021-02-08 10:35:02,757  running on Linux Ubuntu 16.04 xenial
2021-02-08 10:35:02,776 Attached to ip:22
2021-02-08 10:35:02,782  (press Control-C to detach)


(xpra_cmd:11884): Pango-WARNING **: 10:35:03.883: couldn't load font "Bitstream Vera Sans Not-Rotated 14.662109375", falling back to "Sans Not-Rotated 14.662109375", expect ugly output.
2021-02-08 10:35:04,928 UI thread is now blocked
2021-02-08 10:35:04,993 Error: cannot find icon 'xpra'
2021-02-08 10:35:05,060 running, 9 windows, 3 trays
2021-02-08 10:35:05,150 Error: cannot find icon 'clipboard'
2021-02-08 10:35:05,177 Error: cannot find icon 'xpra'
2021-02-08 10:35:05,195 UI thread is running again, resuming
2021-02-08 10:35:05,690 Error: cannot find icon 'clipboard'
...
```
Ad infinitum.

I think it was introduced in the >r28319 sometime

**Comment by totaam** [comment]
Thanks for the report.

Fixed in a24ddbbcedda3db52ae3239c0ac725617153abc1

**Comment by stdedos** [comment]
You don't really need to write this if you don't want to 😉 ^^^^

**Comment by totaam** [comment]
> You don't really need to write this if you don't want to wink ^^^^

Then I don't get to say thanks!

> I totally understand you being bored to do PR's on yourself;

Yeah, I find that weird!

>  however, that stuff works also with plain commits on master too.

Thanks, I'll try it.

**Comment by stdedos** [comment]
> > You don't really need to write this if you don't want to wink ^^^^
> 
> Then I don't get to say thanks!

Oh yeah right 😅 

> > I totally understand you being bored to do PR's on yourself;
> 
> Yeah, I find that weird!

It promotes the use of alternating branches (e.g. master and release/next), and a lot of things based on controlled releases (e.g. automatic changelog by https://github.com/commitizen-tools/commitizen) work like that.

**Comment by stdedos** [comment]
Oh, btw - still happens with tray icons.

Tray > Right-click icons are okay, but tray itself is not okay.

**Comment by stdedos** [comment]
Now fixed 😀
