### ISSUE TITLE
Submenus of the tray menu are broken

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3800]
**Describe the bug**
Commit https://github.com/Xpra-org/xpra/commit/928647c4e125d247764b158138fe1bf7e5da9d4f broke the "Clipboard" and "Start" submenus in the context menu of the tray icon. The other menus work and I currently cannot test the Webcam menu.

**To Reproduce**
1. right click the tray icon
2. The "clipboard" and "start" menu entries do not have a submenu and do not display an arrow indicating a submenu

When reverting the commit or replacing "AyatanaAppIndicator3" with an invalid name (i.e. avoiding AppIndicator) I have the menus again.
The other submenus work as expected.

**System Information (please complete the following information):**
-    Server OS: Debian stable
-    Client OS: Debian testing
-    Xpra Server Version: 4.4.3-r0-1
-    Xpra Client Version: 5.0-r32888-1

**Comment by totaam** [comment]
As I mentioned in the other ticket: I saw this behaviour once with the clipboard menu, but now it is shown every single time - looks like a fluke.

I am reluctant to change the order again between preferring `AyatanaAppIndicator3` over `AppIndicator3` since the former is the newer fork.

**Comment by allo-** [comment]
From what I understand, I think using `AyatanaAppIndicator3` is the right thing, but with it there is a bug affecting these two menus, that requires fixing. That's why I made a separate bug.

I had the "Start" menu not working on another computer with Debian **stable** for a few month some time ago and away thought the versions in Debian stable may be to old, some .desktop files are missing or similar and didn't to anything but used the "run" dialog instead. After some time it was fixed by some upgrade and then it worked.
The problem here is, that I don't see a replacement for the clipboard menu.

I wonder what the common factor is and also why the other menus work fine. The "Start" menu may be changed more dynamically somewhere, but shouldn't the clipboard menu behave just like the other settings menus?

**Comment by totaam** [comment]
@allo- Like I said, above, I can no longer reproduce the problem.

The start menu could just be because your server is not providing the start menu data - you should check with a different client to verify (ie: the html5 client).
This submenu is also populated **after** the connection handshake since the client has to wait for the server to provide the data and this can take several seconds on slower systems  - perhaps you just needed to wait a little bit longer?

The clipboard menu starts disabled and is only enabled after the server handshake if both the client and server support clipboard transfers.
Perhaps the `AyatanaAppIndicator3` is having difficulties with dynamic menus?

**Comment by allo-** [comment]
The start menu of the bug that was fixed in a version some time ago did not work on a debian-stable client and did work on a debian-testing client with the same server. Possibly also affected by other configuration on the client, I am not sure.

The menu now depends on if AyatanaAppIndictor3 is used.

>  Perhaps the AyatanaAppIndicator3 is having difficulties with dynamic menus?

I do not know its internals or API, but it looks like there is some problem building the menu afterward. I wonder if there is some race condition about when the menus are built, a order that needs to be correct, or if *they* just have a bug somewhere.

**Comment by totaam** [comment]
FWIW: the class that builds the tray menu has not changed much since it was added to the codebase ~ 12 years ago.
As for the start menu handling, that's 9 years: 78cd544a98949891c7c16d594022ad994556babc
And this has worked with GTK2, then GTK3, StatusIcon, MS Windows, MacOS, etc..

**Comment by AGI-chandler** [comment]
My issue is the submenu has many of the items disabled and looks like this:
![Screenshot from 2023-09-12 20-41-53](https://github.com/Xpra-org/xpra/assets/27978373/be7259ff-25fe-4991-91a4-9c04d24c8488)

However, if I open Gnome Extensions and toggle `off` the Built-In `Ubuntu AppIndicators` (some of my tray icons disappear but Xpra icon remains) then the submenus light up and are usable.  If I toggle back `on` the `Ubuntu AppIndicators` then my other tray icons come back and the Xpra tray submenus continue to work as well:
![Screenshot from 2023-09-12 20-43-11](https://github.com/Xpra-org/xpra/assets/27978373/7054ecfb-962f-4014-a62f-a44794a3d52f)

Client is running:

- Debian with Xpra:
  - 4.4.6-r29-1

Exhibited on servers running:

- Debian with Xpra:
  - 5.0.1-r0-1

Not exhibited on servers running:

- Debian with Xpra:
  - 4.4.4-r0-1
- CentOS with Xpra:
  - 4.4.6-10.r33693.el8

Is this same issue described here or should I start new issue?
Thanks

**Comment by totaam** [comment]
@AGI-chandler see #3956

The fix is in 5.0.2

**Comment by AGI-chandler** [comment]
@totaam I upgraded the Debian server xpra from 5.0.1-r0-1 to 5.0.2-r0-1 but still seeing the same issue...

**Comment by totaam** [comment]
The fix is client side.
