### ISSUE TITLE
Error loading menu data: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#4092]
**Describe the bug**
A problem populating the menu, that seems to come from missing icons.

**To Reproduce**
- run `xpra start :10`
- Have a missing icon?

**System Information (please complete the following information):**
 - Server OS: Debian stable 
 - Client OS: Debian testing
 - Xpra Server Version: 5.0.4-r0-1
 - Xpra Client Version: 6.0-r34830-1

**Additional context**
Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/menu_provider.py", line 146, in load
    self.get_menu_data(force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/menu_provider.py", line 169, in get_menu_data
    self.menu_data = load_menu()
                     ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 349, in load_menu
    xdg_menu_data = load_xdg_menu_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 461, in load_xdg_menu_data
    entries = load_applications(menu_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 497, in load_applications
    ed = load_xdg_entry(me.DesktopEntry)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 259, in load_xdg_entry
    props : Dict[str,Any] = export(de, (
                            ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 70, in export
    load_entry_icon(props)
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 162, in load_entry_icon
    filename = find_icon(*names)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 180, in find_icon
    find_theme_icon(*names) or \
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 218, in find_theme_icon
    fn = IconTheme.LookupIcon(name, size, theme=theme, extensions=EXTENSIONS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xdg/IconTheme.py", line 405, in LookupIcon
    if distance < minimal_size:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```

**Comment by totaam** [comment]
Already fixed in 360dbf7da3c4b6d647af099f232fa0bd5f9e798d (2 months ago..)

**Comment by allo-** [comment]
Are the Debian packages broken again? I'm not seeing an update for the Debian stable package.

**Comment by totaam** [comment]
This fix is in 6.0 beta and will be in 5.0.5

I am not rushing the stable update because this is not a regression, and only seems to affect Debian and Ubuntu.

**Comment by allo-** [comment]
Still happens with 5.07. The fix in the commit is in the source files, but I guess the icon size comes from another place then.

```
2024-03-12 23:57:04,443 Error loading menu data
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/menu_provider.py", line 146, in load
    self.get_menu_data(force_reload)
  File "/usr/lib/python3/dist-packages/xpra/server/menu_provider.py", line 169, in get_menu_data
    menu_data = self.menu_data = load_menu()
                                 ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 349, in load_menu
    xdg_menu_data = load_xdg_menu_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 461, in load_xdg_menu_data
    entries = load_applications(menu_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 497, in load_applications
    ed = load_xdg_entry(me.DesktopEntry)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 259, in load_xdg_entry
    props : Dict[str,Any] = export(de, (
                            ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 70, in export
    load_entry_icon(props)
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 162, in load_entry_icon
    filename = find_icon(*names)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 180, in find_icon
    find_theme_icon(*names) or \
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 218, in find_theme_icon
    fn = IconTheme.LookupIcon(name, size, theme=theme, extensions=EXTENSIONS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xdg/IconTheme.py", line 405, in LookupIcon
    if distance < minimal_size:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2024-03-12 23:57:05,195 Error in worker thread processing item <bound method BaseWindowModel.guess_content_type of OverrideRedirectWindowModel(1608d6b)>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/server/background_worker.py", line 72, in run
    item()
  File "/usr/lib/python3/dist-packages/xpra/x11/models/base.py", line 412, in guess_content_type
    content_type = guess_content_type(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/server/window/content_guesser.py", line 275, in guess_content_type
    guess_content_type_from_command(window) or \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/server/window/content_guesser.py", line 229, in guess_content_type_from_command
    ctt = load_command_to_type()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/server/window/content_guesser.py", line 197, in load_command_to_type
    xdg_menu = get_menu_provider().get_menu_data(remove_icons=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/server/menu_provider.py", line 169, in get_menu_data
    menu_data = self.menu_data = load_menu()
                                 ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 349, in load_menu
    xdg_menu_data = load_xdg_menu_data()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 461, in load_xdg_menu_data
    entries = load_applications(menu_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 497, in load_applications
    ed = load_xdg_entry(me.DesktopEntry)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 259, in load_xdg_entry
    props : Dict[str,Any] = export(de, (
                            ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 70, in export
    load_entry_icon(props)
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 162, in load_entry_icon
    filename = find_icon(*names)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 180, in find_icon
    find_theme_icon(*names) or \
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xpra/platform/posix/menu_helper.py", line 218, in find_theme_icon
    fn = IconTheme.LookupIcon(name, size, theme=theme, extensions=EXTENSIONS)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/xdg/IconTheme.py", line 405, in LookupIcon
    if distance < minimal_size:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

These are two backtraces in the log, but they seem to be caused by the same bug.

**Comment by totaam** [comment]
This backtrace originates here:
https://github.com/Xpra-org/xpra/blob/14b9ed386d736f2460dcb810e7a39d3891a0a40d/xpra/platform/posix/menu_helper.py#L214-L218
It is impossible for size to be `None` after: `size = Config.icon_size or 32`
Any `None` value ORed with 32 will be 32:
```
$ python -c "print(None or 32)"
32
```

---

So I looked at the `pyxdg` source code, and this particular comparison comes from here:
https://github.com/takluyver/pyxdg/blob/1d23e483ae869ee9532aca43b133cc43f63626a3/xdg/IconTheme.py#L401-L409

My guess is that there's something wrong with the theme you have installed.
This is arguably a bug in `pyxdg` as it falls through and returns `None` from `DirectorySizeDistance` if the theme `Type` is not one of `Fixed`, `Scalable` or `Threshold`:
https://github.com/takluyver/pyxdg/blob/1d23e483ae869ee9532aca43b133cc43f63626a3/xdg/IconTheme.py#L426-L445

I have created a PR: https://github.com/takluyver/pyxdg/pull/20
You can apply this trivial one line change to your existing installation, it should fix things.

**Comment by totaam** [comment]
Missing icons would not be causing this.
An invalid theme type would.

**Comment by allo-** [comment]
I am not completely sure where to look on a headless system, but I have /usr/share/icons/default empty except for a index.theme file with the content:

```
[Icon Theme]
Inherits=Adwaita
```

And Adwaita is installed and looks correct to me.

**Comment by totaam** [comment]
@allo- the commit above tries to continue when pyxdg bugs out.
