### ISSUE TITLE
error preparing connection: list indices must be integers or slices, not DeviceEthernet

### ISSUE THREAD

**Issue by lionkmp** [Xpra-org/xpra#4299]
**Describe the bug**

On my Ubuntu 22.04.4 LTS for some reason I cannot connect to my xpra server anymore. The error I get:

```
2024-07-13 00:02:20,259 error preparing connection: list indices must be integers or slices, not DeviceEthernet
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/base/client.py", line 411, in send_hello
    hello.update(self.make_hello())
  File "/usr/lib/python3/dist-packages/xpra/client/gtk3/client_base.py", line 869, in make_hello
    capabilities = UIXpraClient.make_hello(self)
  File "/usr/lib/python3/dist-packages/xpra/client/gui/ui_client_base.py", line 410, in make_hello
    caps.update(c.get_caps(self))
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/network_state.py", line 136, in get_caps
    default_adapter_type = guess_adapter_type(get_NM_adapter_type(device_name) or device_name)
  File "/usr/lib/python3/dist-packages/xpra/net/device_info.py", line 50, in get_NM_adapter_type
    nmdevice = nmclient.get_devices()[index]
TypeError: list indices must be integers or slices, not DeviceEthernet

```

**To Reproduce**
1. `xpra start :101 --start=/home/lion/.local/bin/bitcoin/bin/bitcoin-qt`
2. `xpra attach ssh://lion@egg/101`

**System Information (please complete the following information):**

Client: Ubuntu 22.04.4 LTS
```
$ python3 --version
Python 3.10.12
$ xpra --version
xpra v6.1-r36031 (g1d987762b4) beta
$ apt policy xpra
xpra:
  Telepítve: 6.1-r36031-1
  Jelölt:    6.1-r36031-1
  Verziótáblázat:
 *** 6.1-r36031-1 100
        100 /var/lib/dpkg/status
     6.0.2-r0-1 500
        500 https://xpra.org jammy/main amd64 Packages
     6.0-r0-1 500
      (Longer output cut)
$ cat /etc/apt/sources.list.d/xpra.sources
Types: deb
URIs: https://xpra.org
Suites: jammy
Components: main
Signed-By: /usr/share/keyrings/xpra.asc
Architectures: amd64 arm64
```
Server: Debian 12
```
$ python3 --version
Python 3.11.2
$ xpra --version
xpra v6.0.2-r0
$ apt policy xpra
xpra:
  Telepítve: 6.0.2-r0-1
  Jelölt:    6.0.2-r0-1
  Verziótáblázat:
 *** 6.0.2-r0-1 500
        500 https://xpra.org bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     6.0-r0-1 500
      (Longer output cut)
$ cat /etc/apt/sources.list.d/xpra.sources 
Types: deb
URIs: https://xpra.org
Suites: bookworm
Components: main
Signed-By: /usr/share/keyrings/xpra.asc
Architectures: amd64 arm64
```

**Additional context**

I'm not sure why the versions are different, I think I followed your install guides, but it was long time ago. Ever since, just APT based updates.  (I have a Debian 12 based Linux too as client OS, from that one this works. Also works from my Windows. Just  the Ubuntu version stopped working recently. My Ubuntu OS version was not updated with major version recently.)

Thank you in advance!

**Comment by totaam** [comment]
Two problems:
* looks like the network-manager API has changed, bc7300c159db90dc2d71b33a0189b8a16aeff5ec should fix that - this will land in a stable release - until it does, perhaps downgrading to 6.x or 5.x will fix this?
* I think you got unlucky and got a 6.1 beta build from the stable channel because I had messed up the repositories: try removing xpra (`apt-get remove xpra`) then installing again (`apt-get install xpra`) and you _should_ be getting 6.0.2

**Comment by totaam** [comment]
34644e57bad788af9dfc4ac12f13de07de103b69 will now also make it possible to skip NM api using `XPRA_NM_API=0 xpra ..`

**Comment by totaam** [comment]
And then I took another look and this particular piece of code did break before: #4165
I'm not sure I trust the API documentation now.. So 34644e57bad788af9dfc4ac12f13de07de103b69 makes it possible to skip all the NM api with `XPRA_NM_API=0`.

**Comment by lionkmp** [comment]
Thank you for the quick response and fixes. Downgrading the 6.0.2 solved that particular problem, and finally I understand why I had a "beta" and how to fix it. :+1: 

But that certain program (bitcoin core Qt) still does not work, but now other programs now work. So I'm sure this should go into a new bugreport (if at all), but please take a look and let me know. The window appears but it's black. I tried another program, and that works (Transmission).

Bitcoin Core starts with a "splash screen" that shows _syncing_ for some minutes, and later on a final program window comes up with menus and GUI. BOTH of these do not work, same black screen and this error repeats if I move the window or try anything:

```

2024-07-13 14:24:02,907 Error drawing on window 1
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/windows.py", line 1601, in _do_draw
    window.draw_region(x, y, width, height, coding, data, rowstride,
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_base.py", line 844, in draw_region
    backing.draw_region(x, y, width, height, coding, img_data, rowstride, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 958, in draw_region
    self.paint_webp(img_data, x, y, width, height, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gl/backing.py", line 1226, in paint_webp
    super().paint_webp(img_data, x, y, width, height, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 600, in paint_webp
    self.idle_add(self.do_paint_rgb, rgb_format, data,
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 169, in idle_add
    raise NotImplementedError()
NotImplementedError
2024-07-13 14:24:02,907 Error processing draw packet
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/windows.py", line 1527, in _draw_thread_loop
    self._do_draw(packet)
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/windows.py", line 1601, in _do_draw
    window.draw_region(x, y, width, height, coding, data, rowstride,
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_base.py", line 844, in draw_region
    backing.draw_region(x, y, width, height, coding, img_data, rowstride, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 958, in draw_region
    self.paint_webp(img_data, x, y, width, height, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gl/backing.py", line 1226, in paint_webp
    super().paint_webp(img_data, x, y, width, height, options, callbacks)
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 600, in paint_webp
    self.idle_add(self.do_paint_rgb, rgb_format, data,
  File "/usr/lib/python3/dist-packages/xpra/client/gui/window_backing_base.py", line 169, in idle_add
    raise NotImplementedError()
NotImplementedError
AssertionError: WebpBufferWrapper out of scope before being freed!
Exception ignored in: 'xpra.codecs.webp.decoder.WebpBufferWrapper.__del__'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/client/mixins/windows.py", line 1526, in _draw_thread_loop
    with log.trap_error(f"Error processing {packet[0]} packet"):
AssertionError: WebpBufferWrapper out of scope before being freed!

```

**Comment by totaam** [comment]
Oh, that's bad. Not sure how that ended up in the repositories.
On the plus side, you should be able to connect by adding `--encodings=all,-webp`.

**Comment by totaam** [comment]
Alternatively, you can run with `--opengl=no`.

**Comment by totaam** [comment]
The trivial fix is in 5930e2994d6d2ecbdeba37dd4587aa24e850fb65.
My concern is that I seen to be unable to trigger the bug, it should have been spotted before the release but somehow it wasn't.

**Comment by totaam** [comment]
Or you could also install from the beta repo, the 6.1 builds don't have this issue.

**Comment by lionkmp** [comment]
Thanks for the quick feedback, the ``--opengl=no`` makes the program work OK.

My report didn't indicate that the messages mentioning WebP were white, while the stack trace were red. Sorry about that, I thought they belong together, but maybe they do not, because this still does not work:``xpra --encodings=all,-webp attach ssh://lion@egg/101``  (Same black screen and same error repeating as above.) (But as I can see from the error and your patch, they all may be unrelated to webp and the patch should be fine to fix this problem after all, regardless whether this webp switch does not work.) Until that I can live with --opengl=no.

Thank you!

**Comment by totaam** [comment]
Yes, `webp` was just one of the encodings affected, the `opengl=no` uses a different backend which does not have this issue.
