### ISSUE TITLE
Unable to launch XPRA from web browser after updating from v5.0.9 to latest release (v6.1.2)

### ISSUE THREAD

**Issue by mint-b** [Xpra-org/xpra#4347]
Hi. 

I am encountering a problem when updating XPRA from v5.0.9 to v6.x.  
The web browser connection stops working.
If I do a fresh install of XPRA v6.x it won’t work. If I then uninstall and install v5.0.9 with the same steps, I can connect correctly. 

Here are the details, first of the working environment and then of the non-working one.

### General Details:
- **Server OS**: Rocky 8.8 (Rocky 8.10, RHEL 8.9 and 8.10 also tested)
- **Client OS**: Windows 10
- **Xpra Server Version**: See full details in steps below…

### The installation process I followed for both versions:

1,) Install the XPRA repo

wget -O /etc/yum.repos.d/xpra.repo https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/rockylinux/xpra.repo

2,) Install XPRA:
	    2.1.) Enable EPEL repos for Rocky (sudo dnf install epel-release)
	    2.2) dnf install xpra
		  `dnf install xpra-5.0.9*   (for v5.0.9)`
		  `dnf install xpra (for the latest version)`

3,) Open firewall ports

```
firewall-cmd --zone=public --add-port=14500/tcp –permanent
firewall-cmd --reload
```

4,) Disable SElinux
Disable from /etc/selinux/config + reboot

5,) After reboot, run these commands
```
sudo systemctl stop xpra.socket
sudo systemctl stop xpra.service
sudo systemctl start xpra.socket
sudo systemctl start xpra.service
sudo systemctl enable xpra.socket
sudo systemctl enable xpra.service
```

6,) Using a web browser I connect to my server (VM in this case)
https://192.168.0.20:14500/connect.html

### 1 -XPRA 5.0.9-10.r5.el8.x86_64 --> Working
 
![image](https://github.com/user-attachments/assets/dfb0823d-99bc-48ba-b3d8-2029b9256765)

**Details of the working installation/version:**

```
# rpm -qa |grep xpra
xpra-client-gtk3-5.0.9-10.r5.el8.x86_64
xpra-client-5.0.9-10.r5.el8.x86_64
xpra-html5-15.1-1.r0.el8.noarch
xpra-server-5.0.9-10.r5.el8.x86_64
xpra-common-5.0.9-10.r5.el8.x86_64
xorg-x11-drv-dummy-0.4.1-1.xpra2.el8.x86_64
xpra-codecs-5.0.9-10.r5.el8.x86_64
xpra-5.0.9-10.r5.el8.x86_64
xpra-codecs-nvidia-5.0.9-10.r5.el8.x86_64
xpra-audio-5.0.9-10.r5.el8.x86_64
xpra-x11-5.0.9-10.r5.el8.x86_64
```

**Socket and Service status:**
```
# sudo systemctl status xpra.socket

● xpra.socket - Xpra Socket
   Loaded: loaded (/usr/lib/systemd/system/xpra.socket; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2024-09-05 16:44:31 CEST; 523ms ago
   Listen: [::]:14500 (Stream)
           /run/xpra/system (Stream)
    Tasks: 0 (limit: 18697)
   Memory: 4.0K
   CGroup: /system.slice/xpra.socket

Sep 05 16:44:31 iqlr8vm systemd[1]: Starting Xpra Socket.
Sep 05 16:44:31 iqlr8vm systemd[1]: Listening on Xpra Socket.


# sudo systemctl status xpra.service

● xpra.service - Xpra System Server
   Loaded: loaded (/usr/lib/systemd/system/xpra.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2024-09-05 16:44:31 CEST; 1s ago
     Docs: https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Service.md
           man:xpra
 Main PID: 43732 (/usr/bin/xpra p)
    Tasks: 5 (limit: 18697)
   Memory: 45.8M
   CGroup: /system.slice/xpra.service
           ├─43732 /usr/bin/xpra proxy :14500 --daemon=no --tcp-auth=sys --ssl-cert=/etc/xpra/ssl-cert.pem --ssl=on --bind=none --auth=peercred --socket-permissions=666 --log-dir=/var/log --pidfile=/run/xpra/proxy/server.pid --debug=
           └─43843 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 4 --print-address 6 --session

Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,415 serving html content from '/usr/share/xpra/www'
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,416 wrote pid 43732 to '/run/xpra/proxy/server.pid'
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,440 xpra is ready.
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,443 xpra proxy server version 5.0.9-r5
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,444  uid=0 (root), gid=0 (root)
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,444  running with pid 43732 on Linux Rocky Linux 8.8 Green Obsidian
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,447 watching for applications menu changes in:
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,447  '/usr/local/share/applications'
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,447  '/usr/share/applications'
Sep 05 16:44:32 iqlr8vm xpra[43732]: 2024-09-05 16:44:32,928 loaded 56 start menu entries from 7 sub-menus in 0.5 seconds


```

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

### 2 - XPRA -6.1.2-10.r1.el8.x86_64 --> NOT working

Following the same installation steps above.

**NOTE:** test done with and without python3-paramiko (dnf install python3-parami*)

**Details of the NOT working installation/version:**

```
rpm -qa | grep xpra
xpra-codecs-6.1.2-10.r1.el8.x86_64
xorg-x11-drv-dummy-0.4.1-1.xpra2.el8.x86_64
xpra-filesystem-6.1.2-10.r1.el8.noarch
xpra-client-6.1.2-10.r1.el8.x86_64
xpra-x11-6.1.2-10.r1.el8.x86_64
xpra-common-6.1.2-10.r1.el8.x86_64
xpra-server-6.1.2-10.r1.el8.x86_64
xpra-client-gtk3-6.1.2-10.r1.el8.x86_64
xpra-codecs-nvidia-6.1.2-10.r1.el8.x86_64
xpra-audio-6.1.2-10.r1.el8.x86_64
xpra-6.1.2-10.r1.el8.x86_64
xpra-html5-15.1-1.r0.el8.noarch
```

**Socket and Service status:**
```

# sudo systemctl status xpra.socket

● xpra.socket - Xpra Socket
   Loaded: loaded (/usr/lib/systemd/system/xpra.socket; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2024-09-06 09:09:33 CEST; 2min 24s ago
   Listen: [::]:14500 (Stream)
           /run/xpra/system (Stream)
    Tasks: 0 (limit: 18697)
   Memory: 4.0K
   CGroup: /system.slice/xpra.socket

Sep 06 09:09:33 iqlr8vm systemd[1]: Starting Xpra Socket.
Sep 06 09:09:33 iqlr8vm systemd[1]: Listening on Xpra Socket.


# sudo systemctl status xpra.service

● xpra.service - Xpra System Server
   Loaded: loaded (/usr/lib/systemd/system/xpra.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2024-09-06 09:09:35 CEST; 2min 25s ago
     Docs: https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Service.md
           man:xpra
 Main PID: 1150 (xpra)
    Tasks: 4 (limit: 18697)
   Memory: 68.7M
   CGroup: /system.slice/xpra.service
           ├─1150 /usr/bin/python3.11 /usr/bin/xpra proxy :14500 --daemon=no --tcp-auth=sys --ssl-cert=/etc/xpra/ssl-cert.pem --ssl=on --bind=none --auth=peercred --socket-permissions=666 --log-dir=/var/log --pidfile=/run/xpra/proxy/ser>
           └─1500 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 4 --print-address 6 --session

Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,266 serving html content from '/usr/share/xpra/www'
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,271 wrote pid 1150 to '/run/xpra/proxy/server.pid'
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,320 Warning: cannot watch for application menu changes without pyinotify:
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,320  No module named 'pyinotify'
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,324 xpra is ready.
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,328 xpra proxy server version 6.1.2-r1
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,328  uid=0 (root), gid=0 (root)
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,329  running with pid 1150 on Linux 4.18.0-477.10.1.el8_8.x86_64
Sep 06 09:09:37 iqlr8vm xpra[1150]: 2024-09-06 09:09:37,329  cpython 3.11
Sep 06 09:09:38 iqlr8vm xpra[1150]: 2024-09-06 09:09:38,597 loaded 56 start menu entries from 7 sub-menus in 1.2 seconds
lines 1-22/22 (END) 
```

**(NOTE: Unlike the previous case with v5.0.9, this command does not automatically finish, it has to be manually killed (Ctrl+c), maybe indicating an issue?)**

After step 6,)  above, I get this error in my web browsers (Firefox, Edge, and Chrome):

 
![image](https://github.com/user-attachments/assets/4556c1ba-fdde-4f61-9005-d9ac0a673a60)

**Looking at the** _/var/log/messages_ **I get the following error:**

```
Sep  6 08:57:35 iqlr8vm systemd[1]: xpra.socket: Succeeded.
Sep  6 08:57:35 iqlr8vm systemd[1]: Closed Xpra Socket.
Sep  6 08:57:35 iqlr8vm systemd[1]: Starting Xpra Socket.
Sep  6 08:57:35 iqlr8vm systemd[1]: Listening on Xpra Socket.
Sep  6 08:57:35 iqlr8vm systemd[1]: Started Xpra System Server.
Sep  6 08:57:35 iqlr8vm systemd[1]: Reloading.
Sep  6 08:57:35 iqlr8vm systemd[1]: Reloading.
Sep  6 09:14:00 iqlr8vm xpra[1150]: 2024-09-06 09:14:00,218 Error: failed to create SSL socket
Sep  6 09:14:00 iqlr8vm xpra[1150]: 2024-09-06 09:14:00,218  from tcp socket: <socket.socket fd=8, family=10, type=1, proto=0, laddr=('::ffff:192.168.0.20', 14500, 0, 0), raddr=('::ffff:192.168.0.19', 51172, 0, 0)>
Sep  6 09:14:00 iqlr8vm xpra[1150]: 2024-09-06 09:14:00,218  no certificate paths specified
Sep  6 09:14:00 iqlr8vm xpra[1150]: 2024-09-06 09:14:00,218  [Errno 2] No such file or directory

```
**NOTE**: one error says that no certificate path is specified, however they are all present in the default directory _(/etc/xpra)_ and everything is default as it is a fresh install.

**Comment by mint-b** [comment]
Thanks totaam for your quick reply!


> Which command?
> `systemctl status`?
> Are you sure this isn't just a terminal size issue? The output is longer, it may just be waiting for you to view the full log to exit?

yes that one. But might not be important. I just thought I would point out that this was a difference between the working version and the non-working version. 



> As a workaround, my guess is that you could disable socket activation and add `--bind-tcp=0.0.0.0:14500,ssl-cert=/path/to..` to the proxy command line.

If I understand you corrcetly I just did this:

1,) Stopped the socket and service
```
sudo systemctl stop xpra.socket

sudo systemctl stop xpra.service
```

2,) Ran this command in the terminal:

`xpra proxy :14500 --daemon=no --tcp-auth=allow --ssl-cert=/etc/xpra/ssl-cert.pem --ssl=on --bind-tcp=0.0.0.0:14500 --auth=allow --socket-permissions=666 --log-dir=/var/log --pidfile=/run/xpra/proxy/server.pid`

and I still get this error:

```
2024-09-06 12:24:57,561 Error: cannot enable SSH socket upgrades
2024-09-06 12:24:57,562  `paramiko` module not found
2024-09-06 12:24:57,562 created tcp socket '0.0.0.0:14500'
2024-09-06 12:24:57,578 serving html content from '/usr/share/xpra/www'
2024-09-06 12:24:57,579 wrote pid 5077 to '/run/xpra/proxy/server.pid'
2024-09-06 12:24:57,585 created unix domain sockets:
2024-09-06 12:24:57,585  '/run/user/0/xpra/iqlr8vm-14500'
2024-09-06 12:24:57,585  '/run/xpra/iqlr8vm-14500'
2024-09-06 12:24:57,585  '/root/.xpra/iqlr8vm-14500'
2024-09-06 12:24:57,585  '/run/xpra/proxy/socket'
2024-09-06 12:24:57,585 created abstract sockets:
2024-09-06 12:24:57,585  '@xpra/14500'
2024-09-06 12:24:57,591 Warning: cannot watch for application menu changes without pyinotify:
2024-09-06 12:24:57,591  No module named 'pyinotify'
2024-09-06 12:24:57,592 xpra is ready.
2024-09-06 12:24:57,599 xpra proxy server version 6.1.2-r1
2024-09-06 12:24:57,599  uid=0 (root), gid=0 (root)
2024-09-06 12:24:57,599  running with pid 5077 on Linux 4.18.0-553.16.1.el8_10.x86_64
2024-09-06 12:24:57,599  cpython 3.11
2024-09-06 12:24:57,883 loaded 56 start menu entries from 7 sub-menus in 0.3 seconds

2024-09-06 12:25:12,832 Error: failed to create SSL socket
2024-09-06 12:25:12,832  from tcp socket: <socket.socket fd=14, family=2, type=1, proto=0, laddr=('192.168.0.20', 14500), raddr=('192.168.0.19', 63039)>
2024-09-06 12:25:12,832  no certificate paths specified
2024-09-06 12:25:12,832  [Errno 2] No such file or directory
```

![image](https://github.com/user-attachments/assets/fa1974ae-150e-4754-baa3-5415ce97c3de)



thanks!

**Comment by totaam** [comment]
I've had success with:
```shell
xpra proxy :14500 --daemon=no --tcp-auth=allow --ssl-cert=./cert.pem --ssl-key=./key.pem --bind-tcp=0.0.0.0:14500 -d ssl
```
As a regular user with the certificate in my current working directory.
(you can copy the system one there for testing)

My guess is that you need both `--ssl-cert=` and `--ssl-key=` ?
I'm not sure why the service file doesn't specify it TBH!

**Comment by mint-b** [comment]
> I've had success with:
> 
> ```shell
> xpra proxy :14500 \
>     --daemon=no --tcp-auth=allow --ssl-cert=./cert.pem --ssl-key=./key.pem --bind-tcp=0.0.0.0:14500 -d ssl
> ```

Thanks for this update!!  I am able to launch the login window from the browser. However now I have another error. It won't recognize exiting users and it won't log in.

I added the .../key.pem... to the "/usr/lib/systemd/system/xpra.service" file such as: (using both ssl-cert.pem and cert.pem)

![image](https://github.com/user-attachments/assets/58209af8-802c-4c14-89fe-fbb52f0f99cc)

and 

![image](https://github.com/user-attachments/assets/e650a32b-af58-45c4-a9ac-249904c00da8)



I also tried disabling the socket and service and running the command...
```
xpra proxy :14500 \
    --daemon=no --tcp-auth=allow --ssl-cert=./cert.pem --ssl-key=./key.pem --bind-tcp=0.0.0.0:14500 -d ssl
```
...in the terminal as you previously suggested, with both the "_/etc/xpra/ssl-cert.pem_ and _/etc/xpra/key.pem_" directory paths and the "_./ssl-cert.pem_  or _./key.pem_" paths after copying them  to the users home folder and assigning read permissions.
I tested with both ssl-cert.pem and cert.pem

In all cases, using socket/service or running the command in the terminal as root or as the desired (test) user, I always get this:

![image](https://github.com/user-attachments/assets/c99e00fe-4ff0-4d41-8b65-fbce2c000ff4)


It is entirely possible that I am missing something obvious, but at this point I'm not sure what it is :-/ 

Thanks in advance!

**Comment by totaam** [comment]
> `invalid username `test`

Is `test` a valid user account?
If not, then I'm not sure that this is going to work, even if using `verify-username=no`.
In any case, the details will be shown in the server log, additional details with `-d auth`.

**Comment by mint-b** [comment]
Hi, Sorry for my delay in responding.



> Is `test` a valid user account?

Yes, it is. I created it for those tests, but for my next test I used a user known to work in the v5.0.9

 

> In any case, the details will be shown in the server log, additional details with `-d auth`.

these are the results from my tests.
I ran it as a command in the terminal and I also edited the service file for the proxy.

**from the terminal:**

```
`2024-09-09 13:50:40,093 socktype=wss, encryption=None, keyfile=None
2024-09-09 13:50:40,138 make_authenticators('tcp', {'uuid': '12342341234563456789a-45689-abcde23456789abcd12-123456789a9abc345678-56789abcde789abc923456789ab0123456789abc9abcd789abc56789', 'username': 'comsearch'}, wss socket: 192.168.0.20:14500 <- 192.168.0.19:53192) socket options={}
2024-09-09 13:50:40,138 creating authenticators ('allow', <module 'xpra.server.auth.allow' from '/usr/lib64/python3.11/site-packages/xpra/server/auth/allow.py'>, <class 'xpra.server.auth.allow.Authenticator'>, {'exec_cwd': '/etc/xpra'}) for tcp
2024-09-09 13:50:40,138 allow : <class 'xpra.server.auth.allow.Authenticator'>({'exec_cwd': '/etc/xpra', 'remote': {'uuid': '12342341234563456789a-45689-abcde23456789abcd12-123456789a9abc345678-56789abcde789abc923456789ab0123456789abc9abcd789abc56789', 'username': 'comsearch'}, 'connection': wss socket: 192.168.0.20:14500 <- 192.168.0.19:53192, 'socket-dirs': ['/run/user/$UID/xpra', '/run/xpra', '~/.xpra']})
2024-09-09 13:50:40,139 allow: verify_username=True, client_username=False
2024-09-09 13:50:40,139 <class 'xpra.server.auth.allow.Authenticator'>({'exec_cwd': '/etc/xpra', 'remote': {'uuid': '12342341234563456789a-45689-abcde23456789abcd12-123456789a9abc345678-56789abcde789abc923456789ab0123456789abc9abcd789abc56789', 'username': 'comsearch'}, 'connection': wss socket: 192.168.0.20:14500 <- 192.168.0.19:53192, 'socket-dirs': ['/run/user/$UID/xpra', '/run/xpra', '~/.xpra']})
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/server/core.py", line 2017, in make_authenticators
    authenticator = aclass(**opts)
                    ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/sys_auth_base.py", line 281, in __init__
    super().__init__(**kwargs)
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/sys_auth_base.py", line 86, in __init__
    raise ValueError("invalid username %r" % (std(remote_username)))
ValueError: invalid username 'comsearch'
2024-09-09 13:50:40,139 instantiating authenticator for tcp
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/server/core.py", line 2052, in verify_auth
    proto.authenticators = self.make_authenticators(socktype, remote, conn)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/server/core.py", line 2017, in make_authenticators
    authenticator = aclass(**opts)
                    ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/sys_auth_base.py", line 281, in __init__
    super().__init__(**kwargs)
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/sys_auth_base.py", line 86, in __init__
    raise ValueError("invalid username %r" % (std(remote_username)))
ValueError: invalid username 'comsearch'
2024-09-09 13:50:40,140 Warning: authentication failed
2024-09-09 13:50:40,140  invalid username 'comsearch'
2024-09-09 13:50:41,141 Disconnecting client 192.168.0.19:53192:
2024-09-09 13:50:41,141  invalid username 'comsearch'
2024-09-09 13:50:41,155 1 packets received (0.9K bytes)
2024-09-09 13:50:41,155 1 packets sent (51 bytes)
2024-09-09 13:50:41,906 New socket connection received
2024-09-09 13:50:41,906  on '/run/user/0/xpra/iqlr8vm-14500'
2024-09-09 13:50:41,907 socktype=socket, encryption=None, keyfile=None
2024-09-09 13:50:41,920 New socket connection received
2024-09-09 13:50:41,920  on '/run/user/0/xpra/iqlr8vm-14500'
2024-09-09 13:50:41,920 socktype=socket, encryption=None, keyfile=None
2024-09-09 13:50:41,937 New socket connection received
2024-09-09 13:50:41,937  on '/run/user/0/xpra/iqlr8vm-14500'
2024-09-09 13:50:41,937 socktype=socket, encryption=None, keyfile=None
2024-09-09 13:50:41,970 make_authenticators('socket', {'uuid': 'badfe5a29a292c3c6db1b3da3ad69475b55db97f18c2a19e6c8440065ad56ecf', 'session-id': '7aa10a77b5a64fa8bc5475364f284cb5'}, socket socket:/run/user/0/xpra/iqlr8vm-14500) socket options={}
2024-09-09 13:50:41,971 processing authentication with (), remaining=(), digest_modes=('xor', 'hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b', 'des', 'kerberos', 'gss', 'u2f'), salt_digest_modes=('hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b')
2024-09-09 13:50:41,971 all 0 authentication modules passed
2024-09-09 13:50:41,978 make_authenticators('socket', {'uuid': 'badfe5a29a292c3c6db1b3da3ad69475b55db97f18c2a19e6c8440065ad56ecf', 'session-id': 'd03dfef9ddb54858b34d92fc7c80e99a'}, socket socket:/run/user/0/xpra/iqlr8vm-14500) socket options={}
2024-09-09 13:50:41,979 processing authentication with (), remaining=(), digest_modes=('xor', 'hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b', 'des', 'kerberos', 'gss', 'u2f'), salt_digest_modes=('hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b')
2024-09-09 13:50:41,979 all 0 authentication modules passed
2024-09-09 13:50:42,000 make_authenticators('socket', {'uuid': 'badfe5a29a292c3c6db1b3da3ad69475b55db97f18c2a19e6c8440065ad56ecf', 'session-id': '8d383c40561f46539af11f507646a1e9'}, socket socket:/run/user/0/xpra/iqlr8vm-14500) socket options={}
2024-09-09 13:50:42,000 processing authentication with (), remaining=(), digest_modes=('xor', 'hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b', 'des', 'kerberos', 'gss', 'u2f'), salt_digest_modes=('hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b')
2024-09-09 13:50:42,000 all 0 authentication modules passed
2024-09-09 13:50:42,040 New socket connection received
2024-09-09 13:50:42,040  on '/run/user/0/xpra/iqlr8vm-14500'
2024-09-09 13:50:42,040 socktype=socket, encryption=None, keyfile=None
2024-09-09 13:50:42,043 make_authenticators('socket', {'uuid': 'badfe5a29a292c3c6db1b3da3ad69475b55db97f18c2a19e6c8440065ad56ecf', 'session-id': '81bf7fbc31344fc7b116fc6ef5ee3690'}, socket socket:/run/user/0/xpra/iqlr8vm-14500) socket options={}
2024-09-09 13:50:42,043 processing authentication with (), remaining=(), digest_modes=('xor', 'hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b', 'des', 'kerberos', 'gss', 'u2f'), salt_digest_modes=('hmac+sha512', 'hmac+sha3_512', 'hmac+sha3_384', 'hmac+sha3_256', 'hmac+sha3_224', 'hmac+sha384', 'hmac+sha256', 'hmac+sha224', 'hmac+blake2s', 'hmac+blake2b')
2024-09-09 13:50:42,043 all 0 authentication modules passed
2024-09-09 13:50:42,081 1 packets received (2.5K bytes)`
```

**And running from the proxy**, I get this:

[20240916_xpra_auth_log_proxy_Rocky8_xpra_v6.1.2-10.txt](https://github.com/user-attachments/files/17009892/20240916_xpra_auth_log_proxy_Rocky8_xpra_v6.1.2-10.txt)


thanks again!

**Comment by totaam** [comment]
> `ValueError: invalid username 'comsearch'`

That's a stricter validation of usernames introduced in v6: #4294
https://github.com/Xpra-org/xpra/blob/5b49aecf41e78d0b4708c782b1a1a0d1ec2787da/xpra/server/auth/sys_auth_base.py#L81-L82

TBH, I haven't tested proxy auth properly lately, maybe 518b2713798a14f2a5d68ed8ec7c73e5a4f68986 helps.
You should be able to get the same result by editing `/etc/sysconfig/xpra` and setting:
```
TCP_AUTH=sys,client-username=yes,verify-username=no
```

**Comment by mint-b** [comment]
```
[comsearch@iqlr8vm ~]$ rpm -qa | grep xpra
xpra-html5-16-1.r0.el8.noarch
xpra-filesystem-6.1.2-10.r1.el8.noarch
xpra-codecs-6.1.2-10.r1.el8.x86_64
xpra-client-6.1.2-10.r1.el8.x86_64
xpra-common-6.1.2-10.r1.el8.x86_64
xpra-server-6.1.2-10.r1.el8.x86_64
xpra-codecs-nvidia-6.1.2-10.r1.el8.x86_64
xpra-6.1.2-10.r1.el8.x86_64
xorg-x11-drv-dummy-0.4.1-1.xpra1.el8.x86_64
xpra-x11-6.1.2-10.r1.el8.x86_64
xpra-client-gtk3-6.1.2-10.r1.el8.x86_64
xpra-audio-6.1.2-10.r1.el8.x86_64
[comsearch@iqlr8vm ~]$

```

I made sure SElinux is disabled.

I tried it 6 ways:

**1.)** Editing /etc/sysconfig/xpra and adding TCP_AUTH=sys,client-username=yes,verify-username=no
**2.)** Leaving /etc/sysconfig/xpra as it was originally and editing /usr/lib/systemd/system/xpra.service  and adding to TCP_AUTH=sys,client-username=yes,verify-username=no
**3.)** Having both _/usr/lib/systemd/system/xpra.service_  and _/etc/sysconfig/xpra_ set to `TCP_AUTH=sys,client-username=yes,verify-username=no
`
I get this same result:

```
# sudo systemctl status xpra.service
● xpra.service - Xpra System Server
   Loaded: loaded (/usr/lib/systemd/system/xpra.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2024-09-16 11:55:47 CEST; 432ms ago
     Docs: https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Service.md
           man:xpra
  Process: 2822 ExecStart=/usr/bin/xpra proxy :14500 --daemon=no --tcp-auth=${TCP_AUTH} --ssl-cert=/etc/xpra/ssl-cert.pem --ssl-key=/etc/xpra/key.pem --ssl=on --bind=none --auth=${AUTH} --socket-permissions=666 --log-dir=/var/log --pidf>
 Main PID: 2822 (code=exited, status=7)

Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 cannot load sys,client-username=yes,verify-username=no auth for 'sys,client-username=yes,verify-username=no'
Sep 16 11:55:46 iqlr8vm xpra[2822]: Traceback (most recent call last):
Sep 16 11:55:46 iqlr8vm xpra[2822]:   File "/usr/lib64/python3.11/site-packages/xpra/server/auth/auth_helper.py", line 49, in get_auth_module
Sep 16 11:55:46 iqlr8vm xpra[2822]:     auth_module = __import__(auth_mod_name, {}, {}, ["Authenticator"])
Sep 16 11:55:46 iqlr8vm xpra[2822]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 16 11:55:46 iqlr8vm xpra[2822]: ModuleNotFoundError: No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 xpra server initialization error:
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928  cannot load authentication module 'sys,client-username=yes,verify-username=no' for 'sys,client-username=yes,verify-username=no': No module named 'xpra.server.auth.sys,client_u>
Sep 16 11:55:47 iqlr8vm systemd[1]: xpra.service: Main process exited, code=exited, status=7/NOTRUNNING
Sep 16 11:55:47 iqlr8vm systemd[1]: xpra.service: Failed with result 'exit-code'.
lines 1-18/18 (END)
```



-----

this line gets my attention.
`ModuleNotFoundError: No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'`

-----

This is the /var/log/messages log:

```
Sep 16 11:55:46 iqlr8vm systemd[1]: Reloading.
Sep 16 11:55:46 iqlr8vm systemd[1]: xpra.socket: Succeeded.
Sep 16 11:55:46 iqlr8vm systemd[1]: Closed Xpra Socket.
Sep 16 11:55:46 iqlr8vm systemd[1]: Starting Xpra Socket.
Sep 16 11:55:46 iqlr8vm systemd[1]: Listening on Xpra Socket.
Sep 16 11:55:46 iqlr8vm systemd[1]: Started Xpra System Server.
Sep 16 11:55:46 iqlr8vm systemd[1]: Reloading.
Sep 16 11:55:46 iqlr8vm systemd[1]: Reloading.
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,903 Error: cannot enable SSH socket upgrades
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,903  `paramiko` module not found
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,917 debug enabled for ['xpra.server.auth.auth_helper', 'auth']
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,917 debug enabled for ['xpra.server.core', 'auth']
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,917 debug enabled for ['xpra.server.proxy.server', 'proxy', 'auth']
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,927 serving html content from '/usr/share/xpra/www'
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,927 get_auth_modules(tcp, ['sys,client-username=yes,verify-username=no'], ..)
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 get_auth_module(sys,client-username=yes,verify-username=no, {..})
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 auth module name for 'sys,client-username=yes,verify-username=no': 'xpra.server.auth.sys,client_username=yes,verify_username=no'
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 cannot load sys,client-username=yes,verify-username=no auth for 'sys,client-username=yes,verify-username=no'
Sep 16 11:55:46 iqlr8vm xpra[2822]: Traceback (most recent call last):
Sep 16 11:55:46 iqlr8vm xpra[2822]:  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/auth_helper.py", line 49, in get_auth_module
Sep 16 11:55:46 iqlr8vm xpra[2822]:    auth_module = __import__(auth_mod_name, {}, {}, ["Authenticator"])
Sep 16 11:55:46 iqlr8vm xpra[2822]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 16 11:55:46 iqlr8vm xpra[2822]: ModuleNotFoundError: No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928 xpra server initialization error:
Sep 16 11:55:46 iqlr8vm xpra[2822]: 2024-09-16 11:55:46,928  cannot load authentication module 'sys,client-username=yes,verify-username=no' for 'sys,client-username=yes,verify-username=no': No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
Sep 16 11:55:47 iqlr8vm systemd[1]: xpra.service: Main process exited, code=exited, status=7/NOTRUNNING
Sep 16 11:55:47 iqlr8vm systemd[1]: xpra.service: Failed with result 'exit-code'.
```


--------


**4.)** I also tried adding client-username=yes,verify-username=no as parameters in the /usr/lib/systemd/system/xpra.service file

`--client-username=yes --verify-username=no`

and I get error:  `no such option: --client-username`

... So I guess that isn't a valid option... I had to try.

---------

**5.)** I tried running the command in the terminal, with the service and socket stopped, both as root and regular user:


```
[root@iqlr8vm ~]# xpra proxy :14500 \
>     --daemon=no --tcp-auth=sys,client-username=yes,verify-username=no --ssl-cert=./cert.pem --ssl-key=./key.pem --bind-tcp=0.0.0.0:14500 -d auth
```
Error:

```
2024-09-16 12:05:26,559 Error: cannot enable SSH socket upgrades
2024-09-16 12:05:26,559  `paramiko` module not found
2024-09-16 12:05:26,559 created tcp socket '0.0.0.0:14500'
2024-09-16 12:05:26,574 debug enabled for ['xpra.server.auth.auth_helper', 'auth']
2024-09-16 12:05:26,575 debug enabled for ['xpra.server.core', 'auth']
2024-09-16 12:05:26,575 debug enabled for ['xpra.server.proxy.server', 'proxy', 'auth']
2024-09-16 12:05:26,587 serving html content from '/usr/share/xpra/www'
2024-09-16 12:05:26,587 get_auth_modules(tcp, ['sys,client-username=yes,verify-username=no'], ..)
2024-09-16 12:05:26,587 get_auth_module(sys,client-username=yes,verify-username=no, {..})
2024-09-16 12:05:26,587 auth module name for 'sys,client-username=yes,verify-username=no': 'xpra.server.auth.sys,client_username=yes,verify_username=no'
2024-09-16 12:05:26,587 cannot load sys,client-username=yes,verify-username=no auth for 'sys,client-username=yes,verify-username=no'
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/auth_helper.py", line 49, in get_auth_module
    auth_module = __import__(auth_mod_name, {}, {}, ["Authenticator"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
2024-09-16 12:05:26,587 xpra server initialization error:
2024-09-16 12:05:26,587  cannot load authentication module 'sys,client-username=yes,verify-username=no' for 'sys,client-username=yes,verify-username=no': No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
[root@iqlr8vm ~]#
```

```
[comsearch@iqlr8vm ~]$ xpra proxy :14500 \
>     --daemon=no --tcp-auth=sys,client-username=yes,verify-username=no --ssl-cert=./cert.pem --ssl-key=./key.pem --bind-tcp=0.0.0.0:14500 -d auth
Warning: XDG_RUNTIME_DIR is not defined
 and '/run/user/1000' does not exist
 using '/tmp'
2024-09-16 12:15:48,209 Error: cannot enable SSH socket upgrades
2024-09-16 12:15:48,209  `paramiko` module not found
2024-09-16 12:15:48,209 created tcp socket '0.0.0.0:14500'
2024-09-16 12:15:48,315 debug enabled for ['xpra.server.auth.auth_helper', 'auth']
2024-09-16 12:15:48,315 debug enabled for ['xpra.server.core', 'auth']
2024-09-16 12:15:48,315 debug enabled for ['xpra.server.proxy.server', 'proxy', 'auth']
2024-09-16 12:15:48,326 serving html content from '/usr/share/xpra/www'
2024-09-16 12:15:48,326 get_auth_modules(tcp, ['sys,client-username=yes,verify-username=no'], ..)
2024-09-16 12:15:48,326 get_auth_module(sys,client-username=yes,verify-username=no, {..})
2024-09-16 12:15:48,326 auth module name for 'sys,client-username=yes,verify-username=no': 'xpra.server.auth.sys,client_username=yes,verify_username=no'
2024-09-16 12:15:48,326 cannot load sys,client-username=yes,verify-username=no auth for 'sys,client-username=yes,verify-username=no'
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/xpra/server/auth/auth_helper.py", line 49, in get_auth_module
    auth_module = __import__(auth_mod_name, {}, {}, ["Authenticator"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
2024-09-16 12:15:48,327 xpra server initialization error:
2024-09-16 12:15:48,327  cannot load authentication module 'sys,client-username=yes,verify-username=no' for 'sys,client-username=yes,verify-username=no': No module named 'xpra.server.auth.sys,client_username=yes,verify_username=no'
[comsearch@iqlr8vm ~]$
```

**6.)** I also tried only adding tcp-auth=sys,client-username=yes   as mentioned in 518b271, (leaving out verify-username=no) and I get the same type of error.


One last question, is there a place where I can see all of the available options for configuring XPRA and the proxy? I remember years ago seeing a very long list here on one of the GitHub pages, but I can no longer find it.

thanks.

**Comment by totaam** [comment]
My bad, I think this does what you want: a7a3acb0cf6f22d80e35890600a227b3f9e38dd3

Though I am now seeing some problems when combining ssl, the proxy and offscreen decoding...

**Comment by mint-b** [comment]
> My bad, I think this does what you want: [a7a3acb](https://github.com/Xpra-org/xpra/commit/a7a3acb0cf6f22d80e35890600a227b3f9e38dd3)

Thanks, I'll try with this when I have a free moment. I will update if I find more related issues or if it seems solved.



> Though I am now seeing some problems when combining ssl, the proxy and offscreen decoding...

is it similar to #3995? I've noticed this in v5.0.9, but I haven't been able to reproduce it step-by-step consistently to be able to report it properly. Happens only in Edge and Chrome, not Firefox.
Also in Firefox and Chrome the left mouse button acts like the right mouse button and opens the context menus for copy/paste, etc..  
In any case I will open different tickets for those when I am able to reproduce them correctly. I don't want to mix them with this issue.

**Comment by totaam** [comment]
I have applied a workaround: https://github.com/Xpra-org/xpra-html5/commit/614c1b538c98268564c60d18c2571ca868f9e70e
But I am still searching for the root cause to fix it properly.

**Comment by totaam** [comment]
The html5 client bug has been fixed - can I close this ticket now?

**Comment by mint-b** [comment]
Many thanks for your help in solving this!! 
I will test it as soon as possible.  Do I test the fixes with the latest beta version? or do I have to modify files manually?

**Comment by totaam** [comment]
@mint-b this is available in [v16.1](https://github.com/Xpra-org/xpra-html5/releases/tag/v16.1) which will hit the stable repo today.

**Comment by mint-b** [comment]
Hi totaam.  thanks for your time with this.

I tried the new stable release today in a fresh and updated install of Rocky 8.10 and I am still unable to login using the proxy.

`[root@iqlr8vm ~]# uname -a
Linux iqlr8vm 4.18.0-553.22.1.el8_10.x86_64 #1 SMP Wed Sep 25 09:20:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
`

[root@iqlr8vm ~]# rpm -qa |grep xpra
xpra-common-6.1.2-10.r1.el8.x86_64
xpra-x11-6.1.2-10.r1.el8.x86_64
xpra-filesystem-6.1.2-10.r1.el8.noarch
xpra-client-6.1.2-10.r1.el8.x86_64
xpra-6.1.2-10.r1.el8.x86_64
xorg-x11-drv-dummy-0.4.1-1.xpra2.el8.x86_64
xpra-codecs-6.1.2-10.r1.el8.x86_64
xpra-html5-16.1-1.r0.el8.noarch
xpra-server-6.1.2-10.r1.el8.x86_64
xpra-client-gtk3-6.1.2-10.r1.el8.x86_64
xpra-audio-6.1.2-10.r1.el8.x86_64
xpra-codecs-nvidia-6.1.2-10.r1.el8.x86_64


1.) I tried the proxy with the default install, without changing anything:
- Didn't work. 
- I had to add `--ssl-key=/etc/xpra/key.pem` to the `/usr/lib/systemd/system/xpra.service`  so it will work.

2,) Tried login without additional changes to config files: 
- Did not work. got this error again 

![image](https://github.com/user-attachments/assets/e144dc3d-3920-468a-9461-06c8a8c6d6b7)

3,) Did the steps above, adding both cases: `TCP_AUTH=sys:client-username=yes` and `TCP_AUTH=sys:client-username=yes:verify-username=no ` in the `/etc/sysconfig/xpra` file:
- Did not work

![image](https://github.com/user-attachments/assets/044903df-363a-483d-a0a7-778c5518d8db)


thanks again!

Here is the log:
[xpra_log_auth_20240926.txt](https://github.com/user-attachments/files/17145128/xpra_log_auth_20240926.txt)


I wonder if I am missing some configuration parameter?  I have unfortunately lost track of all the changes since v5.0.9, so I am not sure if I should have modified something else

**Comment by totaam** [comment]
The proxy fixes recorded here: https://github.com/Xpra-org/xpra/blob/v6.1.x/docs/CHANGELOG.md
Are scheduled for release in 6.1.3
Until then, you can use the 6.2 beta builds or the 5.x LTS.
