### ISSUE TITLE
WM_TAKE_FOCUS messages can have wrong timestamp

### ISSUE THREAD

**Issue by luke-jr** [Xpra-org/xpra#4484]
**Describe the bug**
Somehow xpra is sending applications WM_TAKE_FOCUS with the wrong timestamp. This confuses Qt and causes copy-to-clipboard to fail with `qt.qpa.clipboard: QXcbClipboard::setMimeData: Cannot set X11 selection owner`

It usually only happens after several weeks of uptime. Restarting xpra doesn't seem to help.

**To Reproduce**
1. Wait several weeks. In my most recent occurrence, it began causing issues after 37 days.
2. Open `kwrite` or some other Qt application with copy-to-clipboard functionality
3. Attempt to copy to clipboard.

**System Information (please complete the following information):**
 - Server OS: Linux
 - Client OS: Linux
 - Xpra Server Version: 5.0.10
 - Xpra Client Version: 6.0.1

**Additional context**
Please see "reporting bugs" in the wiki section.

**Comment by totaam** [comment]
Looks like the same issue as #4439

The helpful hint was the 37 days:
```py
round(2**32/1000/60/60/24)
50
```

I think that this is a regression caused by fef8b55d4f0bcde1c923e50087fc070f2d575040 in v5.


The actual code setting the focus is here:
https://github.com/Xpra-org/xpra/blob/d43630dd91c2522c86901cd5285cc52311768a4d/xpra/x11/models/window.py#L926-L955
And the server time is obtained from here:
https://github.com/Xpra-org/xpra/blob/3e25ef46478b533c57b646cfe630809243f0c226/xpra/x11/bindings/window.pyx#L1434-L1445

By inspecting the generated C code, I believe that 3e25ef46478b533c57b646cfe630809243f0c226 should fix this.
Though it may take up to ~50 days to confirm!

**Comment by Simba98** [comment]
Try to reopen this one.
Reproduce it on new launched Xpra 6.2.5 Session:

```
~$ xpra version
Warning: using '/run/user/1694680682' as XDG_RUNTIME_DIR
6.2.5-r0
```

Client: Windows Xpra 6.2.5r0

Tested Program: Qt 5.12.9

              $> Qt5.12.9/MaintenanceTool
              [11331] Warning: QXcbClipboard::setMimeData: Cannot set X11 selection owner

The error message occurs when you select something on the Qt5 window.

If I reboot the system, from my experience (in previous version), it will recover.
Restarting the Xpra server/client will not solve it (I just upgraded installed Xpra 6.2.5, today)

I will keep it for debug.

**Comment by luke-jr** [comment]
I agree with @Simba98 that this appears to not be fixed. With Xpra 6.2.5, clients are still getting the wrong timestamp with WM_TAKE_FOCUS messages.

**Comment by totaam** [comment]
> With Xpra 6.2.5

This is not a supported version.

---

The timestamp we get from `get_server_time` is used here:
https://github.com/Xpra-org/xpra/blob/29e22cbf5fb0d2560e7fa3eb11d2109d18bff8ff/xpra/x11/bindings/window.pyx#L585-L588
And here
https://github.com/Xpra-org/xpra/blob/29e22cbf5fb0d2560e7fa3eb11d2109d18bff8ff/xpra/x11/bindings/send_wm.py#L21-L33

You can ignore the `int` type, this is a Python type hint, not a `C` data type.

**Comment by Simba98** [comment]
> I agree with [@Simba98](https://github.com/Simba98) that this appears to not be fixed. With Xpra 6.2.5, clients are still getting the wrong timestamp with WM_TAKE_FOCUS messages.

I would just like to remind you there is one commit 83171d which is merge into release on v6.3. https://github.com/Xpra-org/xpra/commit/83171d19ecd0f5b85ab5053c923a58a13719effe
Verify with v6.2.5 may missed this.

**Comment by dragonroot** [comment]
I've also hit the `Cannot set X11 selection owner` Qt problem with xpra 6.3.2. In my case, the timestamp value became larger than 0x7FFFFFFF (expected to happen after ~25 days). The culprit of the problem was that `send_wm_take_focus` was trying to handle such values specially, where in reality the X11 timestamp is simply a 32-bit unsigned value and values larger than 0x7FFFFFFF don't require any special handling.

Here's the patch that fixed the problem for me:

```patch
diff --git a/xpra/x11/bindings/send_wm.py b/xpra/x11/bindings/send_wm.py
index 64b9c5f881..21504a52f7 100644
--- a/xpra/x11/bindings/send_wm.py
+++ b/xpra/x11/bindings/send_wm.py
@@ -24,10 +24,6 @@ def send_wm_take_focus(xid: int, timestamp: int = CurrentTime) -> None:
         timestamp = 0
     elif timestamp > 0xFFFFFFFF:
         raise OverflowError(f"invalid time: {timestamp:x}")
-    elif timestamp > 0x7FFFFFFF:
-        timestamp = int(0x100000000 - timestamp)
-        if timestamp >= 0x80000000:
-            timestamp -= 0x80000000
     X11Window.sendClientMessage(xid, xid, False, 0,
                                 "WM_PROTOCOLS",
                                 "WM_TAKE_FOCUS", timestamp)
```

**Comment by totaam** [comment]
Thanks, I've applied it since it fixes things.
But it does raise some questions.
This was added in 2511732c27a71c73bdb9b45a1573c2dfd55e1cef for a timestamp overflow.
See also 368b4e4b4f0d3b2d7d2a02c86ea89111f8644f1e for v5 - perhaps only this part is wrong?
Could this bug really have been lurking for 17 years unnoticed?
Or could this be exacerbated by some toolchain updates? (Cython?)
